girl_home = [
    ["https://v.douyin.com/N9jcoqw/", "0"],
    ["https://v.douyin.com/N9rwGJK/", "0"],
    ["https://v.douyin.com/N9MoTcM/", "0"],
    ["https://v.douyin.com/Nx4dC5H/", "0"],
    ["https://v.douyin.com/Nx4mM2m/", "0"],
    ["https://v.douyin.com/Nx4VnsN/", "0"],
    ["https://v.douyin.com/NQrp5ph/", "0"],
    ["https://v.douyin.com/NCSKgpc/", "0"],
    ["https://v.douyin.com/NXQ2BEF/", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAGTcyBs_MF1p2vK0QB2pUK_N3-huudY2UtA9Shw0o5N8", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAA8kdkwkYpSjvR2AlFDLdVy1352fA_HYNK_mfPRUQuX6c", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAi2L9c6Ug27FzjZoE_zwsJnY7SvNYnHi5ss8on9-_4Jc", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAfuBoNMIBdfYM5KdDvbBdEayoCopxEPYIl7mEjEutVF8", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAN7AlSyqDf3h0_jlPqnd8hsPvOTHIn3d-6PHc2Rzm-Ww", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAMSP7fhJeDXRaTZF_-UCeSmCCV_FUSCzDPzdad7_Jv_I", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAvtNKUOhnLKZiPPHr-eIJ20rglONbh2KSwHiwjTzMhq4", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAnRNzpMXiakl0sd8Jz6GeIAIPcdfszwDUGmcPNIXfZts", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAk80rvs_EJCnjy9kc8g6g6xqGwYUuwBxuOhziJDyOPx8", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAkVwxIWEqdlwZHVx5r4rW9cTIZTe6o152leRAT1gJj68", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAA9JBkh08IQekh4484lICYuOoeyQXTyAuy5f5QLvIYI8", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAmN-OcPiuEft-FoJycaUOAMy5x1N6BAAcZCMpYZuSgOM", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAEJp-gAnWF9eKsAZ91QmA4BJqrIbJwg6pawl0U3QHpIWDVpfjytXizVQPZsCCLOv6", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAgOeOms9eDZosgQd4dUMrxsD53sNhj7q3LA-nqqU0KQs6YUD0H5_OVJmzE6YIVXDK", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAsdwgqV9wtBx5G-iVeQMb0C9jurkGZyRde2PABRLSLiXOKG5edML3SuoP7WdwLZUa", "0"],
    ["https://www.douyin.com/user/MS4wLjABAAAAYcAz-mqV7lPPUN3MpxYXgQgO6MZqmJwM7999FquSqqjsiOVlrmTOVEpDxTwlY-kA", "0"],
]
